extras/bespin-compl usr/share/doc/kde-style-bespin/extras/
extras/kde_infopage.css usr/share/doc/kde-style-bespin/extras/
extras/default-theme-clean.svg.bz2 usr/share/doc/kde-style-bespin/extras/
extras/README usr/share/doc/kde-style-bespin/extras/
extras/macmenu usr/share/doc/kde-style-bespin/extras/
extras/k3b/* usr/share/doc/kde-style-bespin/extras/k3b/
presets/* usr/share/doc/kde-style-bespin/presets/